spring.application.name=booking-backend

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.config.import=optional:file:.env[.properties]

jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=864000000
jwt.header=Authorization
jwt.token-prefix=Bearer
jwt.generate-key=False

spring.flyway.enabled=true
spring.profiles.active=dev
